# Change these first
owner: Leuthra # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Portfolio Site
    url: https://romi.my.id
  - name: API
    url: https://hono.romi.my.id
  - name: CDN Uploader
    url: https://cdn.romi.my.id
  - name: PKL Countdown
    url: https://pkl.romi.my.id
  - name: AC Repair
    url: https://acrepair.romi.my.id
  - name: Docs Template
    url: https://docs.romi.my.id
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime Status**"
  introMessage: Romi Muharom's status page, with real-time response times, uptime and status history.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
